#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.0

provisioner:
  name: chef_zero
  attributes:
    authorization:
      sudo:
        users: [vagrant]

platforms:
  - name: freebsd-10.1
    driver:
      vagrantfiles:
        - Vagrantfile.rb
      ssh:
        shell: '"/bin/sh"'

suites:
  - name: default
    run_list:
      - recipe[bsdznc::default]
