#<% require 'kitchen-sync' %>
---
driver:
  name: vagrant
  require_chef_omnibus: 12.4.0

provisioner:
  name: chef_zero

platforms:
  - name: freebsd-10.1
    driver:
      vagrantfiles:
        - Vagrantfile.rb
      ssh:
        shell: '"/bin/sh"'

suites:
  - name: default
    driver:
      network:
        - ["private_network", {ip: "10.10.12.100"}]
    attributes:
      authorization:
        sudo:
          users: [vagrant]
    run_list:
      - recipe[bsdznc::default]

  - name: znc
    driver:
      network:
        - ["private_network", {ip: "10.10.12.101"}]
    run_list:
      - recipe[bsdznc::znc]
